<?php

/**
 * Generates a stand-in `vendor/autoload.php`.
 *
 * **Not part of a normal deployment.** Real installs run `composer install`,
 * which writes its own `vendor/autoload.php`; this script exists only so the
 * suite can run on a machine where Composer cannot execute.
 *
 * The reason it cannot, on the ePHPm-embedded PHP used to develop this:
 * Composer's `PlatformRepository` scrapes `phpinfo(INFO_MODULES)` for
 * `SSL Version => …` inside the curl section, and this build's `phpinfo()` text
 * output uses line endings that the `^…$` multiline match does not treat as
 * line boundaries. The `.+` therefore runs past the end of the line and
 * Composer derives a platform package name containing newlines, which its own
 * validator then rejects:
 *
 *     Invalid package found during dependency resolution, aborting:
 *     lib-curl-schannel\nzlib version => 1.3.2\nlibssh version => libssh2
 *
 * `curl_version()['ssl_version']` itself is clean ("Schannel"), so this is a
 * `phpinfo()` formatting issue in the embedded SAPI, not a curl one. It is
 * worth reporting upstream — it breaks Composer for every application running
 * under `ephpm php`.
 *
 * Usage: ephpm php tools/vendor-autoload.php
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$vendor = $root . '/vendor';

if (!is_dir($vendor)) {
    fwrite(STDERR, "vendor/ not present — fetch the packages first\n");
    exit(1);
}

$psr4 = [];
$files = [];

foreach (scandir($vendor) ?: [] as $entry) {
    $manifest = $vendor . '/' . $entry . '/composer.json';
    if ($entry === '.' || $entry === '..' || !is_file($manifest)) {
        continue;
    }

    $autoload = json_decode((string) file_get_contents($manifest), true)['autoload'] ?? [];

    foreach ($autoload['psr-4'] ?? [] as $prefix => $paths) {
        foreach ((array) $paths as $path) {
            $psr4[$prefix][] = 'vendor/' . $entry . '/' . rtrim($path, '/');
        }
    }

    foreach ($autoload['files'] ?? [] as $file) {
        $files[] = 'vendor/' . $entry . '/' . $file;
    }
}

// The application's own namespaces, mirroring composer.json.
$psr4['Switchboard\\'][] = 'src';
$psr4['Switchboard\\Tests\\'][] = 'tests';

$export = static fn (mixed $v): string => var_export($v, true);

file_put_contents($vendor . '/autoload.php', <<<PHP
<?php

/**
 * Generated by tools/vendor-autoload.php — a stand-in for Composer's own
 * autoloader. Regenerate rather than edit. A real deployment overwrites this
 * with `composer install`.
 */

declare(strict_types=1);

\$root = dirname(__DIR__);

\$psr4 = {$export($psr4)};

spl_autoload_register(static function (string \$class) use (\$root, \$psr4): void {
    // Longest prefix first, so `Switchboard\\Tests\\` wins over `Switchboard\\`.
    \$prefixes = array_keys(\$psr4);
    usort(\$prefixes, static fn (\$a, \$b) => strlen(\$b) <=> strlen(\$a));

    foreach (\$prefixes as \$prefix) {
        if (!str_starts_with(\$class, \$prefix)) {
            continue;
        }
        \$relative = str_replace('\\\\', '/', substr(\$class, strlen(\$prefix))) . '.php';
        foreach (\$psr4[\$prefix] as \$dir) {
            \$path = \$root . '/' . \$dir . '/' . \$relative;
            if (is_file(\$path)) {
                require \$path;

                return;
            }
        }
    }
});

foreach ({$export($files)} as \$file) {
    require \$root . '/' . \$file;
}

PHP);

echo "wrote vendor/autoload.php (" . count($psr4) . " namespaces, " . count($files) . " files)\n";
